
window.addEventListener('load',function(){
    document.querySelector('#menuDiv').style.display='none';
});
document.querySelector('#menu').addEventListener('click',function(){
    document.querySelector('#menuDiv').style.display='block';
    document.querySelector('#menuDiv').style.backgroundColor='#2a5e88';
    document.querySelector('home').style.display='none';
});
document.querySelector('#startClose').addEventListener('click',function(){
    document.querySelector('#menuDiv').style.display='none';
    document.querySelector('home').style.display='block';
    document.querySelector('body').style.backgroundColor='#f5f5f5';
});
document.querySelector('#endClose').addEventListener('click',function(){
    document.querySelector('#menuDiv').style.display='none';
    document.querySelector('home').style.display='block';
    document.querySelector('body').style.backgroundColor='#f5f5f5';
});